description: "train and pred base"
num_epochs: 5
accum_mod: 2
trn_batch_size: 16
val_batch_size: 32
tst_batch_size: 32
preprocessor:
    preprocessor_type: baseline_kernel
    tokenizer_type: data/dataset/deepset/xlm-roberta-base-squad2/
    max_length: 384
    pad_on_right: true
    stride: 128
postprocessor:
    postprocessor_type: baseline_kernel
splitter:
    splitter_type: kf
    split_num: 5
    shuffle: true
    random_state: 71
dataset:
    dataset_type: chaii
    aug: []
sampler:
    sampler_type: sequential
    trn_sampler_type: random
    val_sampler_type: sequential
    tst_sampler_type: sequential
model:
    model_type: chaii-xlmrb-1
    pretrained_model_name_or_path: data/dataset/deepset/xlm-roberta-base-squad2/
    warmup_epoch: 1
optimizer:
    optimizer_type: adam
    learning_rate: 0.00003
fobj: 
    fobj_type: ce
scheduler:
    scheduler_type: cosine
    max_epoch: 20
    cosine_eta_min: 0.000001
