description: "e007 cumax 0.5 : 0.5 : 2 w/ grad norm 1.0"
train_folds: [0, 1, 2, 3, 4]
accum_mod: 4
trn_batch_size: 16
val_batch_size: 48
tst_batch_size: 48
booster_trn_data:
  - data/dataset/mlqa-hindi-processed/mlqa_hindi.csv
  - data/dataset/mlqa-hindi-processed/xquad.csv
preprocessor:
    tokenizer_type: data/dataset/deepset/xlm-roberta-base-squad2/
model:
    model_type: chaii-qa-seg-xlmrb-1
    pretrained_model_name_or_path: data/dataset/deepset/xlm-roberta-base-squad2/
    max_grad_norm: 1.0
    start_loss_weight: 0.5
    end_loss_weight: 0.5
    segmentation_loss_weight: 2.0
